title: PolderPrinses
description:

url: http://polderprinses.nl
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

defaults:
  -
    scope:
      type: posts
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

navigation:
 - title: Home
   url: /index.html
 - title: Over
   url: /about
 - title: Contact
   url: /contact

social:
   github: polderprinses
   email: daniela@polderprinses.nl
#   twitter: polderprinses
#   facebook: danielahofman

google_analytics: "UA-8287349-5"
